### PR TITLE
drop versions below PHP 7.2

### PR DESCRIPTION
**Pull request by abbadon1334**
i think this must be done

### CODE REVIEW

**Comment by DarkSide666** [comment]
Why not support PHP 7.0 and 7.1 ?

**Comment by abbadon1334** [comment]
> Why not support PHP 7.0 and 7.1 ?

because of this : https://www.php.net/supported-versions.php, prior of this i see that atk4/data drop support for php below 7.2.

We can leave this to support >7.0 and let composer resolve requirements if used with other packages.

I open this issue while I was showing to one of my dev the library and i see that it was required 5.6.
After that i see yours on same subject but with drop for 7.0 and i decide to leave it open.

**Comment by DarkSide666** [comment]
Yeah, probably you're right about 7.2. If data don't support php <7.2, then it's useless to try to run api on 7.0 or 7.1.

Please also add fix for travis.yml (remove 7.0, 7.1 and maybe add 7.3) and let @romaninsh decide what to do with this.

**Comment by abbadon1334** [comment]
@romaninsh in travis i removed the lines targeting php version for coverage, please check it.

**Comment by DarkSide666** [comment]
@abbadon1334 Why did you remove code coverage sending? I think it was fine, just needed to change 7.0 to 7.2.

**Comment by abbadon1334** [comment]
Coverage is back, sorry. I see a losing of coverage, if you want to merge this PR, i will look further in the issue and i will open another one only to increase coverage, because i think api must have higher rate of testing.
Moreover with all the microservice request of the community and with last addiction of atk4/data *action* probably will be used more.

**Review by DarkSide666 — APPROVED** [review]
now all looks good, merging

**Pull request merged**
